# Generated by Django 4.0.3 on 2022-05-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('fork', models.CharField(max_length=200, null=True)),
                ('Part', models.ManyToManyField(to='rowery.parts')),
                ('producent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowery.producent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowery.types')),
            ],
        ),
    ]
