# Generated by Django 4.0.3 on 2022-05-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.RenameField(
            model_name='producent',
            old_name='Marka',
            new_name='producent',
        ),
        migrations.RemoveField(
            model_name='osprzęt',
            name='Frame',
        ),
        migrations.RemoveField(
            model_name='osprzęt',
            name='Wheel',
        ),
        migrations.RemoveField(
            model_name='osprzęt',
            name='shox',
        ),
        migrations.AddField(
            model_name='osprzęt',
            name='forks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='osprzęt',
            name='frame',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='osprzęt',
            name='wheel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rowery.types'),
        ),
    ]
