# Generated by Django 4.0.3 on 2022-05-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowery', '0002_types_delete_model_rename_marka_producent_producent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=200, null=True)),
                ('forks', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wheel', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Osprzęt',
        ),
        migrations.RemoveField(
            model_name='producent',
            name='model',
        ),
        migrations.AddField(
            model_name='rower',
            name='Producent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowery.producent'),
        ),
        migrations.AddField(
            model_name='rower',
            name='Wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowery.wheel'),
        ),
        migrations.AddField(
            model_name='rower',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowery.types'),
        ),
    ]
