# Generated by Django 4.0.3 on 2022-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowery', '0003_rower_wheel_delete_osprzęt_remove_producent_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producent',
            name='producent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='Wheel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
