# Generated by Django 4.0.3 on 2022-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowery', '0004_alter_producent_producent_alter_wheel_wheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rower',
            name='Rower',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
